[build-system]
requires = ["hatchling>=1.25.0"]
build-backend = "hatchling.build"

[project]
name = "nvidia-hackathon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "huggingface-hub",
    "numpy",
    "streamlit",
    "torch",
    "transformers>=5.0.0,<=5.3.0",
    "accelerate",
    "open_clip_torch",
    "pillow",
    "mamba-ssm==2.2.5",
    "timm",
    "causal-conv1d",
]

[project.scripts]
nvidia-hackathon = "nvidia_hackathon.cli:main"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["nvidia_hackathon"]
